# Generated by Django 5.2.5 on 2025-08-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_especialidade', models.CharField(max_length=30)),
                ('descricao_especialidade', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medico', models.CharField(max_length=30)),
                ('endereco_medico', models.CharField(max_length=60)),
                ('telefone_medico', models.CharField(max_length=13)),
                ('email_medico', models.CharField(max_length=60)),
                ('ddn_medico', models.DateField(max_length=8)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('especialidade', models.ManyToManyField(to='medico.especialidade')),
            ],
        ),
    ]
